### ISSUE TITLE
README / Wiki Tings

### ISSUE THREAD

**Issue by sannibunny** [doofenshmirtz-deco-inc/OnBoard#127]
# README
- [ ] Paragraph on general UI style things
- [ ] More pizzaz
    - [ ] Description of the project
    - [ ] Screenshots
- [ ] Link team portfolio?

# Wiki 
These should be a general what components are involved, what the main features are (screenshots with brief descriptions should suffice). 

- [ ] Courses
    - [ ] Learning Resources
    - [ ] Announcements
    - [ ] Course Staff (?)
- [ ] Messaging 
- [ ] Video Chat
- [ ] Dashboard
- [ ] Calendar

**Comment by TomCranitch** [comment]
too late now
